"use client";

import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
  },
  header: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4f46e5', // text-indigo-600
    textAlign: 'center',
    marginBottom: 5,
  },
  subHeader: {
    fontSize: 14,
    color: '#64748b', // text-slate-500
    textAlign: 'center',
    marginBottom: 20,
  },
  line: {
    height: 1,
    backgroundColor: '#cbd5e1',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: 15,
    marginBottom: 8,
    color: '#1e293b',
  },
  text: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#334155',
    marginBottom: 5,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 9,
    color: '#94a3b8',
    textAlign: 'center',
  }
});

interface ReportProps {
  reportContent: string;
}

export const ReportPDF = ({ reportContent }: ReportProps) => {
  // Simple heuristic to split sections (split by double newlines or based on uppercase headers)
  const paragraphs = reportContent.split('\n').filter(p => p.trim() !== '');

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>Leukemia Detector AI</Text>
        <Text style={styles.subHeader}>Automated Diagnostic Clinical Report</Text>
        <View style={styles.line} />
        
        {paragraphs.map((para, i) => {
          // If the line is short and all uppercase, treat it as a bold title
          if (para.length < 50 && para === para.toUpperCase()) {
            return <Text key={i} style={styles.sectionTitle}>{para}</Text>;
          }
          return <Text key={i} style={styles.text}>{para}</Text>;
        })}

        <Text style={styles.footer} fixed>
          Generated by AI System on {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
};
